### PR TITLE
Refactor using Sourcery

### PR DESCRIPTION
**Pull request by Archmonger**
This PR uses [Sourcery](https://sourcery.ai/) to automatically refactor our code to minimize memory usage and improve readablity.

### CODE REVIEW

**Comment by Archmonger** [comment]
Also I recommend merging PRs using "Squash and Merge" so there is a sensible commit blame in the commit logs.

**Comment by marksie1988** [comment]
> Also I recommend merging PRs using "Squash and Merge" so there is a sensible message in the commit logs.

Yep I normally disable other merge types but forgot on this repo, I will update that now. 

Also taken a look at sourcery and never heard of it but I like what it does and seems very efficient so will merge this.

**Comment by Archmonger** [comment]
I definitely would recommend taking a look at using Sourcery as both an editor plugin and directly integrating it as a GH Repository App.

[Here's an example of the kind of metrics](https://github.com/Archmonger/Conreq/pull/69#issuecomment-960825262) you can get on each PR.

Quickly becoming one of my favorite new code suggestion/refactoring tool (RIP DeepCode 😢).

**Comment by marksie1988** [comment]
Oh nice, 

I think I will look into this some more and get it implemented :) thanks for showing this!

**Pull request merged**
