### PR TITLE
feat: added type hints

### PR DESCRIPTION
**Pull request by marksie1988**
## Description

This PR Adds Type hints. 

Some arguments have been updated to allow better support of type hints, this change will only allow correct values to be specified for these items listed below:
- `sort_dir` 
- `sort_keys` 
- `artist_monitor`
- `commands` 

Now accepts datetime instead of strings where a date is required. 

## Related issues

- #105 

## Motivation and Context

By adding support for type hints the module is easier to use and ensure the correct data is provided / returned. 

## How has this been tested

Testing still on-going

## Types of changes

- [ ] Docs change / refactoring.
- [ ] Non-breaking change (fix or feature that wouldn't cause existing functionality to change/break).
- [x] Breaking change (fix or feature that would cause existing functionality to change/break).

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes don't generate new warnings.
- [x] I have read the [CONTRIBUTING](https://github.com/totaldebug/.github/blob/master/docs/CONTRIBUTING.md) document.

### CODE REVIEW

**Comment by Archmonger** [comment]
Honestly not entirely sure how asserts improve anything here, besides making things a bit visually ugly.

**Comment by marksie1988** [comment]
> Honestly not entirely sure how asserts improve anything here, besides making things a bit visually ugly.

The asserts mean we can have the correct type for all on the returns, without it I would need to just use Any which in my eyes defeats the point of using types. 

That said, I do agree that it's ugly and seems unnecessary but seems this is a limitation with typing, there are quite a few posts about it online.

**Comment by Archmonger** [comment]
Given this unfortunate fact...

In the interests of [DRY](https://www.digitalocean.com/community/tutorials/what-is-dry-development), we should have a helper function that is basically `assert_or_return`.

**Comment by marksie1988** [comment]
> Given this unfortunate fact...
> 
> In the interests of [DRY](https://www.digitalocean.com/community/tutorials/what-is-dry-development), we should have a helper function that is basically `assert_or_return`.

Yea that is what I'm going to work on next.

**Comment by Archmonger** [comment]
Might not be able to review this week - I'm currently in the process of moving houses. I'll get to it as soon as possible.

**Pull request merged**
