### PR TITLE
PyArr Async Support

### LINKED ISSUE #67: convert to async
Convert the project to allow asynchronous tasks

### LINKED ISSUE #91: Add tests and codecov
We really should have tests on this project.

A fork of pyarr labled [aiopyarr](https://github.com/tkdrob/aiopyarr) has a fairly in-depth test configuration. The developer [has mentioned](https://github.com/home-assistant/core/issues/51390#issuecomment-1010489250) that we can use his tests in exchange for a mention.

### LINKED ISSUE #92: Add more built-in exceptions
We're missing a few exception types compared to [aiopyarr](https://github.com/tkdrob/aiopyarr).

- [ ] InvalidCommand
- [ ] CannotCancelCommand

### PR DESCRIPTION
**Pull request by Archmonger**
This PR will...
- Add type hinting
- Add CI tests for all endpoints
- Add tests for checking parity between sync/async code
- fix #67
- fix #91 
- fix #92 

We should also look into procedurally generating docstrings based on type hints.

### CODE REVIEW

**Comment by Archmonger** [comment]
I found an interesting resource that may allow for sharing sync/async source. I will look at this later.
https://sobolevn.me/2020/06/how-async-should-have-been#combining-the-two

**Comment by acortelyou** [comment]
> I found an interesting resource that may allow for sharing sync/async source. I will look at this later. https://sobolevn.me/2020/06/how-async-should-have-been#combining-the-two

Interesting article! The approach here looks like it avoids a lot of the duplicated code:
https://sobolevn.me/2020/10/higher-kinded-types-in-python#real-life-use-case

**Comment by Archmonger** [comment]
Note to self: Need to rstrip("/") within the RequestHandler

**Comment by Archmonger** [comment]
This PR is significantly out of date.

If I was to restart efforts on this, I would create a new PR anyways so I'm closing this off.

**Pull request closed without merging**
