### PR TITLE
v0.9.4

### PR DESCRIPTION
**Pull request by Archmonger**
# v0.9.4

### Sonarr New Features

- More robust addSeries
- API Calls
  - setCommand 
    - Options Available: RefreshSeries, RescanSeries, EpisodeSearch, SeasonSearch, SeriesSearch, DownloadedEpisodesScan, RssSync, RenameFiles, RenameSeries, Backup, missingEpisodeSearch
  - updSeries
  - updEpisode
  - del_episode_file_by_episode_id

### Radarr New Features

- More robust addMovie
- API Calls
  - setCommand
    - Options Available: RefreshMovie, RescanMovie, MoviesSearch, DownloadedMoviesScan, RssSync, RenameFiles, RenameMovie, CutOffUnmetMoviesSearch, NetImportSync, missingMoviesSearch
  - updMovie

### CODE REVIEW

**Comment by Archmonger** [comment]
Directly closes #45 and #27 
Indirectly closes #25 , #24 , #23 , #22 , #21 , #20 

Remaining issues should only be #30 and #40 . Awaiting PR to complete these last two, which will encompass revision v0.10.0 or v1.0.0 depending on your preference.

**Comment by marksie1988** [comment]
Tha ks for running through this, haven't had the time I would have liked to finish off this wrapper.

Could I ask that the docs are updated to fit as notice here that the idea is to use the `setCommand` instead of the refresh etc etc.

Thanks for the input.

**Comment by Archmonger** [comment]
Sure, I can update the documentation. Are we referring to the docs on [https://docs.totaldebug.uk/PyArr/](https://docs.totaldebug.uk/PyArr/)?

**Comment by marksie1988** [comment]
Yes that's correct, it's all under the docs folder of this repo.

**Comment by Archmonger** [comment]
Alright. I'll update the docs tomorrow!

**Comment by marksie1988** [comment]
Great, thank you.

**Comment by Archmonger** [comment]
Skipped the documentation for del_episode_file_by_episode_id, since I intend to significantly rework the following functions soon:

- get_episode_files_by_series_id
- get_episode_file_by_episode_id
- del_episode_file_by_episode_id
- push_release

**Comment by marksie1988** [comment]
This looks good thanks, I will run through testing tomorrow.

**Pull request merged**
